### ISSUE TITLE
Crash when placing Teleporting Rail

### ISSUE THREAD

**Issue by MisterShawn** [shadowfacts/ExtraRails#5]
Forge: 12.20.0.2279
ExtraRails: 1.11-1.2.1

I was testing the mod and placed a teleporting rail next to a direction rail and crashed. Also crashes when trying to reload the world.

https://gist.github.com/sdaddy/30e3314726d23329b06b8bf8ba634dde

**Comment by shadowfacts** [comment]
The `net.drpmedieval` mod is broken and using `null` for a `Capability` instance.
